apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadjlua1752-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadjlua1752-tenant-component
    app.kubernetes.io/part-of: loadjlua1752-tenant-app
  name: loadjlua1752-tenant-component
  namespace: loadjlua1752-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: loadjlua1752-tenant-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: loadjlua1752-tenant-component
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images:64301d15f9ad4db18f0a7112731c6281
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
