apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadjlua1752-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadjlua1752-tenant-component
    app.kubernetes.io/part-of: loadjlua1752-tenant-app
  name: loadjlua1752-tenant-component
  namespace: loadjlua1752-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadjlua1752-tenant-component
    weight: null
status: {}
